.\" decode man page
.\" Caeli Massey - Fall 2018
.\" Last edited Dec. 6, 2017

.TH Decode 1 "Dec 6 2018" "CSCI 241" "Oberlin College"

.B decode
\- A program that will decompress/decode a file compressed usiing Huffman compression, printing
the decoded output.

.SH SYNOPSIS
.B ./decode <input_file> [output_file]

.SH DESCRIPTION
Decode will read in a text file (specified either as the first parameter at the
time of execution or through redirection), decompress its contents, and print the
decoded output to a specified output file (set similarly to the input file).

.SH AUTHORS
Caeli Massey

.SH BUGS
None known!

