.\" encode man page
.\" Caeli Massey - Fall 2018
.\" Last edited Dec. 6, 2017

.TH Encode 1 "Dec 6 2018" "CSCI 241" "Oberlin College"

.B encode
\- A program that compressed a file using huffman compiling, orinting the encoded version.

.SH SYNOPSIS
.B ./encode <input_file> [output_file]

.SH DESCRIPTION
Encode will read in a text file (specified either as the first parameter at the
time of execution or through redirection), compress its contents using Huffman
compression, and print the encoded output to a specified output file (set
similarly to the input file).

.SH AUTHORS
Caeli Massey

.SH BUGS
None known!
